# 0.Introduction



*   Python is a great general-purpose programming language on its own, but with the help of a few popular libraries (numpy, scipy, matplotlib) it becomes a **powerful** environment for scientific computing.



# 1.Numpy

## Outline


* Arrays
* Array indexing
* Array math
* **Documentation**

In [ ]:
import numpy as np

## Arrays

* A numpy array is a **grid** of values, all of the **same type**, and is **indexed by a tuple of nonnegative integers**.
* We can initialize numpy arrays from **nested Python lists**, and access elements using **square brackets**.

In [ ]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array
print(a)

b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(type(b), b.shape, b[0], b[1], b[1][0], b[1,0])
print(b)

In [ ]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a,'\n')

b = np.ones((2,2))   # Create an array of all ones
print(b,'\n')

c = np.full((2,2), 7) # Create a constant array
print(c,'\n')

d = np.eye(2)        # Create a 2x2 identity matrix
print(d,'\n')

e = np.random.random((2,2)) # Create an array filled with random values
print(e,'\n')


## Array indexing

* **Slicing**: Numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array.
* A slice of an array is a **view** into the same data, so modifying it **will modify the original array**.

In [ ]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

In [ ]:
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1]) 

* Boolean array indexing: This type of indexing is used to select the elements of an array that **satisfy some condition**.




In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

# We can do all of the above in a single concise statement:
print(a[a > 2])

## Array math

* Basic mathematical functions operate **elementwise** on arrays, and are available both **as operator overloads and as functions**.

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y),'\n')

# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y),'\n')

# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y),'\n')

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y),'\n')

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x),'\n')

* Matrix Operations

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

# Inner product of vectors;
print(np.dot(x, y))
print(x @ y,'\n')

# Transpose of a Matrix
print(x)
print("transpose\n", x.T)

## [Documentation](https://numpy.org/doc/stable/reference/)

# 2.SciPy

* As non-professional programmers, scientists often tend to re-invent the wheel, which leads to buggy, non-optimal, difficult-to-share and unmaintainable code. By contrast, Scipy’s routines are optimized and tested, and should therefore be used when possible.

[Documentation](https://docs.scipy.org/doc/scipy/reference/api.html)

In [ ]:
#STEP1: Find SVD function's documentation from the link above
#STEP2: define a arbitary 3x2 matrix
#STEP3: use the SVD function decompose the matrix into its three svd components
#STEP4: Convert the middle component to a diagonal matrix from the array
#STEP5: Reconstruct original matrix by multiply all the components
#STEP6: Print Original and reconstructed matrix and check if both are same 

# 3.Numba

## Introduction

* Numba provides the ability to speed up applications with high performance functions written directly in Python.
* With a few simple annotations, array-oriented and math-heavy Python code can be just-in-time (JIT) optimized to achieve performance similar to C, C++ and Fortran, without having to switch languages or Python interpreters.
* Numba works at the function level.
* Numba’s main features are:
    * On-the-fly code generation (at import time or runtime, at the user’s preference)
    * Native code generation for the CPU (default) and GPU hardware
    * Integration with the Python scientific software stack (thanks to NumPy)





## Just-in-time Compiling

* Numba’s central feature is the numba.jit() decoration. Using this decorator, it is possible to mark a function for optimization by Numba’s JIT compiler.
* Decorators are a way to uniformly modify functions in a particular way. You can think of them as functions that take functions as input and produce a function as output. See the [Python reference documentation](https://docs.python.org/3/reference/compound_stmts.html#function-definitions) for a more information.
* The returned value is bound to the function name instead of the function object. 

In [ ]:
# Python implementation of bubblesort for NumPy arrays.
def bubblesort(X):
    #REMOVED
    for end in range(N, 1, -1):
        for i in range(end - 1):
            #REMOVED
            if cur > X[i + 1]:
                tmp = X[i]
                X[i] = X[i + 1]
                #REMOVED

In [ ]:
import numpy as np

# Data
original = np.arange(0.0, 10.0, 0.01, dtype='f4')
shuffled = original.copy()
np.random.shuffle(shuffled)

# Testing
sorted = shuffled.copy()
bubblesort(sorted)
print(np.array_equal(sorted, original))

In [ ]:
# Time Profiling
%timeit -n 1 -r 1 sorted[:] = shuffled[:]; bubblesort(sorted) 

In [ ]:
# Lets JIT it
from numba import jit
@jit
def bubblesort_numba(X):
    #COPY CODE FROM bubblesort(X) HERE


In [ ]:
# Time Profiling
%timeit -n 1 -r 1 sorted[:] = shuffled[:]; bubblesort_numba(sorted)

In [ ]:
# Time Profiling
%timeit -n 10 -r 1 sorted[:] = shuffled[:]; bubblesort_numba(sorted)

* Using the decorator in this way will defer compilation until the first function execution, so the first execution will be significantly slower.
* Numba will infer the argument types at call time, and generate optimized code based on this information. Numba will also be able to compile separate specializations depending on the input types.

## Function Signatures

* It is also possible to specify the signature of the Numba function.
* This can produce slightly faster code as the compiler does not need to infer the types.
* However the function is no longer able to accept other types.
* This is useful if you want fine-grained control over types chosen by the compiler (for example, to use single-precision floats).

In [ ]:
from numba import jit, int32, float64

@jit(float64(int32, int32)) #f8(i4, i4)
def f(x, y):
    # A somewhat trivial example
    return (x + y) / 3.14

f(1, 3)

1.2738853503184713

Challenge : See if function signarures can improve performance for the bubblesort_numba function we had above. Report the difference in fastest run time according to timeit.

In [ ]:
# Lets Sign it and Define it
#IMPORT TYPES HERE 
#ADD DECORATOR WITH FUNCTION SIGNATURE HERE - Hint : Input is an array and output is void, for array of int32 you can write 'int32[:]' as type
def bubblesort_numba_defined(X):
    #COPY CODE FROM bubblesort(X) HERE

In [ ]:
# Time Profiling
#ADD TIMEIT STATEMENT HERE

1 loop, best of 1: 1.81 ms per loop


## Compilation Modes

* Numba has two compilation modes: nopython mode and object mode.
* In nopython mode, the Numba compiler will generate code that does not access the Python C API. This mode produces the highest performance code, but requires that the native types of all values in the function can be inferred.
* In object mode, the Numba compiler generates code that handles all values as Python objects and uses the Python C API to perform all operations on those objects. Code compiled in object mode will often run no faster than Python interpreted code.
* Numba will by default automatically use object mode if nopython mode cannot be used for some reason. Rather than fall back to object mode, it is sometimes preferrable to generate an error instead. By adding the nopython=True keyword, it is possible to force Numbe to do this:

In [ ]:
#STEP1: COPY BLOCK FROM ABOVE
#STEP2: import Decimal from decimal
#STEP3: ADD LINE "val = Decimal(100)" as the first line of the function definition
#STEP4: TIMEIT
#STEP5: Add "val = val + 1" as the first line of innermost for loop
#STEP6: TIMEIT

In [ ]:
# Time Profiling
#ADD TIMEIT STATEMENT HERE

# Detailed Guides



*   [Numpy](https://cs231n.github.io/python-numpy-tutorial/#numpy)
*   [SciPy](https://scipy-lectures.org/intro/scipy.html)
*   [Numba](https://nyu-cds.github.io/python-numba/)



# Self-Promotion

* LinkedIn: www.linkedin.com/in/ping-jeet
* Email: ping.jeet@gmail.com